# https://taskfile.dev
# https://github.com/mdouchement/checksum

version: '3'

vars:
  VERSION: 0.2.0
  REVISION: { sh: git rev-parse HEAD }

env:
  GO111MODULE: on
  CGO_ENABLED: 0

tasks:
  clean:
    desc: Clean project
    cmds:
      - rm -rf ./dist

  build-all:
    desc: Build all binaries
    cmds:
      - task: clean
      - mkdir -p dist
      # Supported dist:    go tool dist list
      - |
        archs=(amd64 arm64)
        oses=(linux darwin openbsd freebsd netbsd)

        for os in ${oses[@]}
        do
          for arch in ${archs[@]}
          do
            env GOOS=${os} GOARCH=${arch} go build -ldflags "{{.LDFLAGS | splitList "\n" | join " "}}" -o ./dist/arx-${os}-${arch} .
            ( cd ./dist && checksum --algs="sha256" --append-to checksum.txt arx-${os}-${arch} )
          done
        done
      - |
        archs=(amd64 arm64)
        oses=(windows)

        for os in ${oses[@]}
        do
          for arch in ${archs[@]}
          do
            env GOOS=${os} GOARCH=${arch} go build -ldflags "{{.LDFLAGS | splitList "\n" | join " "}}" -o ./dist/arx-${os}-${arch}.exe .
            ( cd ./dist && checksum --algs="sha256" --append-to checksum.txt arx-${os}-${arch}.exe )
          done
        done
    vars:
      LDFLAGS: |
        -s
        -w
        -X main.version={{.VERSION}}
        -X main.revision={{ printf "%.7s" .REVISION }}
        -X main.date={{now | date "2006-01-02~15:04:05"}}
